### ISSUE TITLE
Wrong "build" script

### ISSUE THREAD

**Issue by mlc-mlapis** [contember/engine#176]
Running `npm run contember instance:up` leads to some errors because the content of `package.json` supposes the existence of `./scripts/all-instances.sh`, but there is no one after installation. What is the expected platform to be used?

```
{
  "scripts": {
    "contember": "contember",
    "build": "tsc --noEmit && ./scripts/all-instances.sh admin/build-webpack"
  },
  "devDependencies": {
    "@contember/cli": "^0.11.2"
  },
  "dependencies": {
    "@contember/schema": "^0.11.2",
    "@contember/schema-definition": "^0.11.2"
  }
}
```

**Comment by VojtaStanek** [comment]
Which command were used to create the project? It looks like you created it with administration which is not publicly available.

**Comment by mlc-mlapis** [comment]
@VojtaStanek No. I used `npm run contember instance:up`, as described on https://docs.contember.com/intro/getting-started.

Is it supposed to use only a Linux platform? No Mac or Windows, right?

**Comment by VojtaStanek** [comment]
First of all, thank for trying out Contember. It is currently under heavy development (much heavier than it may seem from activity in this repository) and we will be offering much better experience with new features and services soon. But don't be afraid to [send us a message](https://www.contember.com/contact/) if you have a specific use-case or want to know more.

Nevertheless, removing ` && ./scripts/all-instances.sh admin/build-webpack` from the file _might_ fix the issue for you (it's there for building administration which is not yet public). It should work on all mentioned platforms, but it's tested only on linux (also inside windows subsystem for linux).

**Comment by VojtaStanek** [comment]
This part has been totally reworked, it should be resolved now.
