### ISSUE TITLE
Fail to open Docker Composer | Windows WSL | Ubuntu 20

### ISSUE THREAD

**Issue by yashiel** [contember/engine#273]
I'm getting this error when trying to start quick-start guide,

![image](https://user-images.githubusercontent.com/72464215/167317399-d39b66b8-cd5a-47be-911f-7f0ab2786717.png)

**Comment by VojtaStanek** [comment]
Hi Yashi!

Thanks for trying out Contember! It looks like an issue with your local installation of Docker, which we use to run Contember Engine. Can you try the solutions which are proposed in the following link? Note that there are two solutions - renaming the `.docker` directory and restarting WSL. https://stackoverflow.com/a/68260405/5058658 

Let me know if it helped.
