### ISSUE TITLE
Run cli using docker

### ISSUE THREAD

**Issue by michalhosna** [contember/engine#33]
I would like to see an official way to run cli from docker. 

I created a docker image for myself https://github.com/michalhosna/mhdockerfiles/tree/master/contember-cli), but there is no supported way I could find to run the instances because cli relies on being able to run the docker-compose command

```shell
❯ docker run --rm -it -v "$PWD:$PWD" -w "$PWD" mhdockerfiles/contember-cli:contember0.7.6_node14.2.0-alpine_v1 instance:up
Error: spawn docker-compose ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by matej21** [comment]
Hi, there is a official docker image [contember/cli](https://hub.docker.com/r/contember/cli) with a bundled docker-compose. You can also try this simple [wrapper script](https://raw.githubusercontent.com/contember/contember/master/packages/cli/contember-docker.sh).

I will add info to the doc.
