### ISSUE TITLE
Command migrations:amend not working

### ISSUE THREAD

**Issue by Thommas2316** [contember/engine#343]
Hello,

we've used `migrations:amend` until we ported to 1.2.0-alpha.16 in this format: `migrations:amend <project-name> --yes`.
It always correctly amended last migration (created with `migrations:diff`). 

However after porting to 1.2.0-alpha.16 it does not work anymore. Inspecting the format for `migrations:amend` it seems it changed and it mentions the name of migration (`migrations:amend [migration] ...`). Ot it did always, but I didn't notice...

Anyway, when I run it as I used to (project name only) or with name of last migration (either name provided to diff of name of json file without extension) it returns error `No migration to amend`.
If I run it without any params, it returns following error:

![image](https://user-images.githubusercontent.com/3959662/200109800-20059d04-ed53-48c6-a8c8-12c943c807c0.png)

So, I'm doing as the cli instructed me and filing a bug report :D 

What am I missing ? I also tried both notations in https://docs.contember.com/reference/engine/schema/migrations#amending-a-migration but both failed in same manner as described above.

Thank you for your time to take a look into this.

**Comment by matej21** [comment]
Thanks for a bug report! will release a new version today.

**Comment by matej21** [comment]
Released as 1.2.0-alpha.18
