### ISSUE TITLE
Allow users to change email

### ISSUE THREAD

**Issue by VojtaStanek** [contember/engine#521]
Currently there is no mutation in tenant API to change their email (or I haven't found it).

**Comment by matej21** [comment]
Hi, the mutation is available in 1.4 (which is currnetly in beta), see https://github.com/contember/engine/blob/302a09ebde472fd0c6bef4de6a05c516012cdf9f/packages/engine-tenant-api/src/schema/tenant.graphql.ts#L29

**Comment by VojtaStanek** [comment]
Thanks!
